name = "SpacecraftGames"
uuid = "6e41399c-043b-478c-b0ff-bfcb964fb2f9"
authors = ["BennetOutland <bennet.outland@pm.me> and contributors"]
version = "1.0.0-DEV"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DifferentialGames = "497f78f8-f326-11f0-3aad-a3ebf6911431"
DifferentialGamesBase = "a9dd1e63-b4ad-4579-bca8-3a609f3d87b9"
DifferentialGamesBaseSolvers = "b83b0c57-42fa-43ab-a182-d5be40f43772"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SpacecraftDynamics = "cc5c844c-0595-4d2f-9df6-d129cc96db37"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorTypes = "0.12.1"
Dates = "1.11.0"
DifferentialGames = "1.0.0"
DifferentialGamesBase = "1.0.0"
DifferentialGamesBaseSolvers = "1.0.0"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.11.0"
Reexport = "1.2.2"
Rotations = "1.7.1"
SpacecraftDynamics = "1.0.0"
SparseArrays = "1.11.0"
StaticArrays = "1.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
